version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: gateway
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - redis
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
