version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-inventory
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: inventory
    ports:
      - 27019:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb_data:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        # - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  mongodb_data:
  redis_data:
